Updated to Debug Toolbar 1.8
aldryn/aldryn-django-debug-toolbar pull request #4
Opened 2017-07-06 16:31 UTC by evildmp

Changes:

* installs Django Debug Toolbar 1.8
* fixes #3, an issue with middleware ordering
* fixes an issue with the `license='BSD'` in setup.py, that was raising an error in local development
* simplified test for actvation in aldryn_config.py
* changed authorship to reflect author of addon package rather than Django Debug Toolbar

2017-07-07 08:08 UTC, stefanfoulis requested changes

2017-07-07 08:08 UTC, stefanfoulis commented on aldryn_config.py
> +                settings["MIDDLEWARE_CLASSES"].index("django.middleware.gzip.GZipMiddleware") + 1,
This will throw an ValueError if ``django.middleware.gzip.GZipMiddleware`` is not in the list.

2017-07-07 08:08 UTC, stefanfoulis commented on aldryn_config.py
>      enable_debug_toolbar = forms.CheckboxField(
We should probably remove the field from the form here, and configure from an environment variable instead.

2017-07-12 07:08 UTC, stefanfoulis approved these changes
Looks good implementation wise now. I didn't know about the top/bottom of middleswares thing with django-debug-toolbar.
A description in the form that better reflects why this option even exists may be needed.
I'd still like the enable/disable of django-debug-toolbar to be an environment variable, but that we can leave as out-of-scope for this PR.

2017-07-12 07:47 UTC, GaretJax approved these changes
Some minor cosmetic changes; I'll leave it up to you if you want to spend time on it now. ;-)

2017-07-12 07:47 UTC, GaretJax commented on aldryn_config.py
> +        help_text="Position in the middleware list",
Please consistently use single quotes (except where the string contains a single quote itself). Also below.

2017-07-12 07:47 UTC, GaretJax commented on aldryn_config.py
> +            if "django.middleware.gzip.GZipMiddleware" in middleware and debug_toolbar_middleware_position == "top":
Waaay too long. :)

2017-07-12 07:47 UTC, GaretJax commented on aldryn_config.py
> +
Please don't add newlines here (and before the else)

2017-07-12 07:47 UTC, GaretJax commented on aldryn_config.py
> +
Please remove the empty line here.

2017-07-12 07:47 UTC, GaretJax commented on aldryn_config.py
> +
Please remove this empty line.

2017-07-17 12:56 UTC, jmelett commented on aldryn_django_debug_toolbar/__init__.py
> +__version__ = "1.8.0.4"
Version bumps should be done in separate commit

2017-07-17 13:15 UTC, merged